version: '2'
services:
  mysql:
      image: "mysql:5.7"
      volumes:
        - "/usr/local/mysql/data:/var/lib/mysql"
      environment:
        - MYSQL_ROOT_PASSWORD=mysql_pass1234567890
      container_name: "mysql"
      ports:
        - 3306:3306
  ghost:
      image: "quay.io/danfercf/ghost-pvpgn-x64"
      volumes:
        - "/usr/local/ghost/maps:/usr/local/ghost/maps"
        - "/usr/local/ghost/replays:/usr/local/ghost/replays"
      environment:
        - SERVEPORT= 6116
      container_name: "ghost"
      command: ["./ghost.sh"]
      ports:
        - 6114:6114
        - 6116:6116
        - 6117:6117
      links:
        - mysql:db
networks:
  default:
      external:
          name: pvpgn_default
