version: '2'
services:
  ghost:
      image: "quay.io/danfercf/ghost-pvpgn-x64"
      volumes:
        - "/usr/local/ghost/maps:/usr/local/ghost/maps"
        - "/usr/local/ghost/replays:/usr/local/ghost/replays"
      environment:
        - SERVEPORT= 6116
      container_name: "ghost"
      command: ["./ghost.sh"]
      ports:
        - 6114:6114
        - 6116:6116
        - 6117:6117
networks:
  default:
      external:
          name: pvpgn_default
